const I=n=>{const d={home:'<path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.8V21h14V9.8"/><path d="M9 21v-7h6v7"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/>',check:'<path d="m5 12 4 4L19 6"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.09A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.09A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88L4.2 6.66l2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.09A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.16.37.38.7.66.98.28.28.62.5 1 .62H21v4h-.09A1.7 1.7 0 0 0 19.4 15Z"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',back:'<path d="m15 18-6-6 6-6"/>',money:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 9h.01M17 15h.01"/><circle cx="12" cy="12" r="2.5"/>',chart:'<path d="M3 3v18h18"/><path d="m7 16 4-5 4 3 5-7"/>',file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h6"/>',alert:'<path d="M10.3 2.9 1.8 17a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 2.9a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/>',logout:'<path d="M10 17l5-5-5-5"/><path d="M15 12H3"/><path d="M21 19V5a2 2 0 0 0-2-2h-6"/>',building:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M9 8h1M14 8h1M9 12h1M14 12h1M9 16h1M14 16h1"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',eye:'<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>',trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6"/>',edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/>',lock:'<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',brief:'<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18"/>'};return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${d[n]||d.file}</svg>`};
const BRL=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const pct=v=>`${Number(v||0).toFixed(1).replace('.',',')}%`;
const clone=o=>JSON.parse(JSON.stringify(o));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const now=new Date(), mk=(y,m)=>`${y}-${String(m).padStart(2,'0')}`, cur=mk(now.getFullYear(),now.getMonth()+1);
const prevMonth=k=>{let[y,m]=k.split('-').map(Number);m--;if(m===0){m=12;y--}return mk(y,m)};
const nextMonth=k=>{let[y,m]=k.split('-').map(Number);m++;if(m===13){m=1;y++}return mk(y,m)};
const monthName=k=>{const[y,m]=k.split('-').map(Number);return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(y,m-1,1)).replace(/^./,c=>c.toUpperCase())};
const seed={loggedIn:false,role:'master',view:'dashboard',selectedCompany:null,tab:'overview',month:cur,filter:'all',search:'',companies:[
{id:'c1',name:'Mercado do João',document:'12.345.678/0001-90',contact:'joao@mercado.com',revenueMode:'individual',expenseEnabled:true,expenseMode:'category',customRevenueCategories:[],customExpenseCategories:['Embalagens']},
{id:'c2',name:'Studio Ana',document:'23.456.789/0001-14',contact:'ana@studio.com',revenueMode:'monthly',expenseEnabled:false,expenseMode:'category',customRevenueCategories:['Mentorias'],customExpenseCategories:[]},
{id:'c3',name:'Mecânica Silva',document:'34.567.890/0001-18',contact:'silva@mecanica.com',revenueMode:'daily',expenseEnabled:true,expenseMode:'individual',customRevenueCategories:[],customExpenseCategories:['Peças','Lubrificantes']},
{id:'c4',name:'Barbearia Carlos',document:'45.678.901/0001-09',contact:'carlos@barbearia.com',revenueMode:'individual',expenseEnabled:true,expenseMode:'individual',customRevenueCategories:[],customExpenseCategories:[]}],entries:[],closings:[],submissions:[]};
function addSeed(){const p=prevMonth(cur);seed.entries.push(
{id:'e1',companyId:'c1',type:'revenue',month:cur,date:`${cur}-02`,description:'Vendas balcão',category:'Vendas',amount:7200},{id:'e2',companyId:'c1',type:'revenue',month:cur,date:`${cur}-07`,description:'Vendas semana',category:'Vendas',amount:8650},{id:'e3',companyId:'c1',type:'revenue',month:cur,date:`${cur}-11`,description:'Vendas balcão',category:'Vendas',amount:6600},{id:'e4',companyId:'c1',type:'expense',month:cur,date:`${cur}-03`,description:'Mercadorias',category:'Mercadorias',amount:6800},{id:'e5',companyId:'c1',type:'expense',month:cur,date:`${cur}-05`,description:'Funcionários',category:'Funcionários',amount:5100},{id:'e6',companyId:'c1',type:'expense',month:cur,date:`${cur}-06`,description:'Aluguel',category:'Aluguel',amount:2200},{id:'e7',companyId:'c1',type:'expense',month:cur,date:`${cur}-09`,description:'Energia',category:'Energia',amount:1180},
{id:'e8',companyId:'c1',type:'revenue',month:p,date:`${p}-02`,description:'Total mês anterior',category:'Vendas',amount:20800},{id:'e9',companyId:'c1',type:'expense',month:p,date:`${p}-05`,description:'Despesas mês anterior',category:'Outras',amount:14100},
{id:'e10',companyId:'c2',type:'revenue',month:cur,date:`${cur}-01`,description:'Total do mês',category:'Serviços',amount:14200},{id:'e11',companyId:'c2',type:'revenue',month:p,date:`${p}-01`,description:'Total do mês',category:'Serviços',amount:13100},
{id:'e12',companyId:'c3',type:'revenue',month:cur,date:`${cur}-05`,description:'Serviços do dia',category:'Serviços',amount:37800},{id:'e13',companyId:'c3',type:'expense',month:cur,date:`${cur}-05`,description:'Peças e insumos',category:'Fornecedores',amount:22800},
{id:'e14',companyId:'c4',type:'revenue',month:cur,date:`${cur}-03`,description:'Serviços',category:'Serviços',amount:11450},{id:'e15',companyId:'c4',type:'expense',month:cur,date:`${cur}-04`,description:'Operação',category:'Outras',amount:6200});
seed.submissions.push({companyId:'c2',month:cur,confirmedAt:new Date().toISOString()},{companyId:'c4',month:cur,confirmedAt:new Date().toISOString()});seed.closings.push({companyId:'c4',month:cur,analysis:'Faturamento manteve estabilidade e os custos ficaram controlados.',attention:'Acompanhar insumos no próximo mês.',recommendation:'Revisar preços dos serviços com maior consumo de produto.',closed:true})}
addSeed();
function normalizeState(x){x.submissions=x.submissions||[];x.companies=(x.companies||[]).map(c=>Object.assign({customRevenueCategories:[],customExpenseCategories:[]},c));return x}
function load(){try{const r=localStorage.getItem('central-financeira-v1-2')||localStorage.getItem('central-financeira-v1-1');return normalizeState(r?Object.assign(clone(seed),JSON.parse(r)):clone(seed))}catch{return normalizeState(clone(seed))}}let state=load();
function save(){try{localStorage.setItem('central-financeira-v1-2',JSON.stringify(state))}catch(e){console.warn(e)}}
function company(id){return state.companies.find(c=>c.id===id)}function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function entriesFor(id,type,month=state.month){return state.entries.filter(e=>e.companyId===id&&(!type||e.type===type)&&(e.month||e.date.slice(0,7))===month)}
const DEFAULT_REVENUE_CATEGORIES=['Vendas','Serviços','Outras receitas'];const DEFAULT_EXPENSE_CATEGORIES=['Mercadorias','Fornecedores','Funcionários','Pró-labore / retirada','Aluguel','Energia','Água','Internet','Impostos','Marketing','Transporte','Tarifas','Outras'];
function totals(id,month=state.month){const rev=entriesFor(id,'revenue',month).reduce((s,e)=>s+Number(e.amount||0),0),exp=entriesFor(id,'expense',month).reduce((s,e)=>s+Number(e.amount||0),0);return{rev,exp,balance:rev-exp,expenseRatio:rev?(exp/rev*100):0}}
function change(a,b){if(!b)return null;return (a-b)/b*100}
function closingFor(id,month=state.month){return state.closings.find(x=>x.companyId===id&&x.month===month)}
function submissionFor(id,month=state.month){return (state.submissions||[]).find(x=>x.companyId===id&&x.month===month)}
function isClosed(id,month=state.month){return !!closingFor(id,month)?.closed}
function isDataLocked(id,month=state.month){return isClosed(id,month)||!!submissionFor(id,month)}
function missingFor(c,month=state.month){const m=[];if(!entriesFor(c.id,'revenue',month).length)m.push('Receitas não informadas');if(c.expenseEnabled&&!entriesFor(c.id,'expense',month).length)m.push('Despesas não informadas');return m}
function pendingText(c,month=state.month){if(isClosed(c.id,month))return'Mês concluído';const sub=submissionFor(c.id,month),miss=missingFor(c,month);if(sub)return closingFor(c.id,month)?'Análise em andamento':'Aguardando sua análise';if(miss.length)return miss.join(' • ');return'Aguardando confirmação do cliente'}
function statusFor(id,month=state.month){const cl=closingFor(id,month),sub=submissionFor(id,month);if(cl?.closed)return['Fechado','closed','closed'];if(sub&&cl)return['Em análise','info','analysis'];if(sub)return['Pronto para análise','ok','ready'];if(entriesFor(id,null,month).length)return['Preenchendo dados','info','filling'];return['Aguardando dados','wait','waiting']}
function categoriesFor(c,type){const base=type==='revenue'?DEFAULT_REVENUE_CATEGORIES:DEFAULT_EXPENSE_CATEGORIES,custom=type==='revenue'?(c.customRevenueCategories||[]):(c.customExpenseCategories||[]);return [...new Set([...base,...custom])]}
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function setMonth(k){state.month=k;save();render()}function moveMonth(n){setMonth(n<0?prevMonth(state.month):nextMonth(state.month))}
function setView(v){state.view=v;state.selectedCompany=null;state.role='master';save();render()}function openCompany(id,tab='overview'){state.selectedCompany=id;state.tab=tab;state.role='master';save();render()}function setTab(t){state.tab=t;save();render()}
function login(){state.loggedIn=true;save();render()}function logout(){state.loggedIn=false;state.role='master';state.selectedCompany=null;save();render()}
function render(){const app=document.getElementById('app');if(!state.loggedIn){app.innerHTML=loginHtml();document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();login()};return}app.innerHTML=state.role==='client'?clientShell():masterShell()}
function loginHtml(){return `<div class="login"><section class="login-hero"><div class="brand"><div class="brandmark">LG</div>Central Financeira</div><div class="login-copy"><small>ACOMPANHAMENTO FINANCEIRO</small><h1>Um acompanhamento financeiro moderno, claro e adaptável para cada cliente.</h1><p>Configure o nível de controle de cada empresa, acompanhe os dados do mês e transforme números em uma entrega consultiva.</p></div><div style="font-size:10px;color:#9FB2E1">V1.6 • Visual MED 12.1</div></section><section class="login-side"><div class="login-card"><h2>Acessar plataforma</h2><p>Entre como usuário Master para administrar a carteira e acompanhar a operação do mês.</p><form id="loginForm"><div class="field"><label>E-mail</label><input class="input" type="email" value="contador@luidgabriel.com.br" required></div><div class="field"><label>Senha</label><input class="input" type="password" value="12345678" required></div><button class="btn btn-primary btn-block">Entrar como Master ${I('arrow')}</button></form><div class="notice"><b>Demonstração local:</b> esta versão não está conectada ao Supabase. Não use dados reais de clientes.</div></div></section></div>`}
function monthCtl(){return `<div class="monthctl"><button onclick="moveMonth(-1)">‹</button><div class="monthlabel">${monthName(state.month)}</div><button onclick="moveMonth(1)">›</button></div>`}
function masterShell(){const inside=!!state.selectedCompany;return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brandmark">LG</div>Central Financeira</div><div class="navtitle">Gestão</div>${nav('dashboard','home','Visão geral')}${nav('companies','users','Clientes')}${nav('closings','check','Fechamentos')}<div class="navtitle">Sistema</div>${nav('settings','settings','Configurações')}<div class="sidebottom"><div class="usercard"><div class="avatar">LG</div><div><strong>Luid Gabriel</strong><span>Super Admin</span></div></div><button class="navbtn" onclick="logout()">${I('logout')} Sair</button></div></aside><main class="main"><header class="topbar"><div class="crumb">Central Financeira <span>›</span><strong>${inside?esc(company(state.selectedCompany)?.name):titleView()}</strong></div><div class="topright">${monthCtl()}<div class="avatar">LG</div></div></header><div class="content">${inside?workspace():mainView()}</div></main></div>`}
function nav(v,i,l){return `<button class="navbtn ${state.view===v&&!state.selectedCompany?'active':''}" onclick="setView('${v}')">${I(i)} ${l}</button>`}function titleView(){return({dashboard:'Visão geral',companies:'Clientes',closings:'Fechamentos',settings:'Configurações'})[state.view]||'Visão geral'}function mainView(){if(state.view==='companies')return companiesHtml();if(state.view==='closings')return closingsHtml();if(state.view==='settings')return settingsHtml();return dashboardHtml()}
function allRows(){return state.companies.map(c=>{const t=totals(c.id),s=statusFor(c.id);return Object.assign({},c,t,{s})})}
