'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import CompleteControlAppV2 from './CompleteControlAppV2';
import { neonTest } from '../lib/neon-test-client';
import {
  loadCompleteV34Data, updateFinanceObligationSafe, createInstallmentPlanV2,
  cancelInstallmentRemainingV2, createRecurringRuleV2, generateRecurringV2,
  stopRecurringRuleV3, normalizeCompleteError
} from '../lib/neon-complete-control-v34';
import { localToday } from '../lib/neon-complete-control';
import styles from './CompleteControlAppV34.module.css';

const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const dateBR=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
const monthNow=()=>localToday().slice(0,7);
const addMonths=(date,months)=>{const d=new Date(`${String(date).slice(0,10)}T12:00:00`);d.setMonth(d.getMonth()+months);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

function Icon({name}){const p={today:<><path d="M4 5h16v15H4z"/><path d="M8 3v4M16 3v4M4 10h16"/></>,statement:<><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></>,installment:<><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M7 10h10M7 14h4"/></>,repeat:<><path d="M17 2l4 4-4 4"/><path d="M3 11V9a3 3 0 0 1 3-3h15"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a3 3 0 0 1-3 3H3"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,back:<path d="m15 18-6-6 6-6"/>,edit:<><path d="m4 20 4-1 11-11-3-3L5 16z"/><path d="m14 6 3 3"/></>,plus:<path d="M12 5v14M5 12h14"/>,refresh:<><path d="M20 7h-5V2"/><path d="M20 7a8 8 0 1 0 1 8"/></>};return <svg viewBox="0 0 24 24" className={styles.icon}>{p[name]||p.today}</svg>}

export default function CompleteControlAppV35(){
  const session=neonTest.auth.useSession(); const activeOrganizationId=session.data?.session?.activeOrganizationId||null; const user=session.data?.user||null;
  const [workspace,setWorkspace]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[detail,setDetail]=useState(null),[modal,setModal]=useState(null);
  const refresh=useCallback(async()=>{if(!user||!workspace)return;setBusy(true);setError('');try{const next=await loadCompleteV34Data(activeOrganizationId);if(next.reload){window.location.reload();return}setData(next)}catch(e){setError(normalizeCompleteError(e))}finally{setBusy(false)}},[user?.id,activeOrganizationId,workspace]);
  useEffect(()=>{if(workspace)refresh()},[workspace,refresh]); useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t)},[toast]);
  async function run(fn,message){setBusy(true);setError('');try{await fn();const next=await loadCompleteV34Data(activeOrganizationId);setData(next);setModal(null);setDetail(null);setToast(message)}catch(e){const m=normalizeCompleteError(e);setError(m);setToast(m)}finally{setBusy(false)}}
  return <div className={styles.root}><CompleteControlAppV2/>
    {!workspace&&<div className={styles.launcher}><button onClick={()=>setWorkspace('today')}><Icon name="today"/><span><b>Hoje</b><small>Agenda financeira</small></span></button><button onClick={()=>setWorkspace('statement')}><Icon name="statement"/><span><b>Extrato</b><small>Por conta</small></span></button><button onClick={()=>setWorkspace('installments')}><Icon name="installment"/><span><b>Parcelamentos</b><small>Planos e parcelas</small></span></button><button onClick={()=>setWorkspace('recurring')}><Icon name="repeat"/><span><b>Recorrências</b><small>Despesas e receitas fixas</small></span></button></div>}
    {workspace&&<Workspace workspace={workspace} data={data} busy={busy} error={error} onClose={()=>{setWorkspace(null);setDetail(null)}} onRefresh={refresh} onDetail={setDetail} onModal={setModal} onRun={run}/>} 
    {detail&&data&&<ObligationDrawer obligation={detail} data={data} onClose={()=>setDetail(null)} onEdit={()=>setModal({type:'edit',obligation:detail})}/>} 
    {modal?.type==='edit'&&<EditObligationModal obligation={modal.obligation} data={data} busy={busy} onClose={()=>setModal(null)} onSave={form=>run(()=>updateFinanceObligationSafe({obligationId:modal.obligation.id,...form}),'Obrigação atualizada com histórico.')} />}
    {modal?.type==='new-plan'&&<InstallmentModal data={data} busy={busy} onClose={()=>setModal(null)} onSave={form=>run(()=>createInstallmentPlanV2(form),'Parcelamento criado.')} />}
    {modal?.type==='cancel-plan'&&<ReasonModal title="Cancelar saldo restante" text="Parcelas abertas ou parciais serão canceladas; baixas já realizadas permanecem no histórico." busy={busy} onClose={()=>setModal(null)} onSave={reason=>run(()=>cancelInstallmentRemainingV2({planId:modal.plan.id,reason}),'Saldo restante do parcelamento cancelado.')} />}
    {modal?.type==='new-recurring'&&<RecurringModal data={data} busy={busy} onClose={()=>setModal(null)} onSave={form=>run(()=>createRecurringRuleV2(form),'Recorrência criada e obrigações geradas.')} />}
    {modal?.type==='stop-recurring'&&<StopRecurringModal busy={busy} onClose={()=>setModal(null)} onSave={(reason,cancelScope)=>run(()=>stopRecurringRuleV3({ruleId:modal.rule.id,cancelScope,reason}),'Recorrência encerrada.')} />}
    {toast&&<div className={styles.toast}>{toast}</div>}
  </div>
}

function Workspace({workspace,data,busy,error,onClose,onRefresh,onDetail,onModal,onRun}){const company=data?.companies?.[0];const companyId=company?.id;const accounts=data?.accounts.filter(x=>x.companyId===companyId)||[];const obligations=data?.obligations.filter(x=>x.companyId===companyId)||[];return <div className={styles.overlay}><section className={styles.workspace}><header><div className={styles.headLeft}><button onClick={onClose}><Icon name="back"/></button><div><span>Controle Completo • V3 + V4</span><h1>{{today:'Hoje',statement:'Extrato por conta',installments:'Parcelamentos',recurring:'Recorrências'}[workspace]}</h1><p>{{today:'O que precisa da sua atenção agora.',statement:'Movimentações e saldo depois de cada evento.',installments:'Uma compra ou venda, várias obrigações reais.',recurring:'Compromissos mensais que alimentam automaticamente o contas a pagar/receber.'}[workspace]}</p></div></div><div className={styles.headActions}><button onClick={onRefresh} disabled={busy}><Icon name="refresh"/></button><button onClick={onClose}><Icon name="close"/></button></div></header>{error&&<div className={styles.error}>{error}</div>}{!data?<div className={styles.loading}>Carregando…</div>:<div className={styles.content}>{workspace==='today'&&<TodayView obligations={obligations} accounts={accounts} onDetail={onDetail}/>} {workspace==='statement'&&<StatementView accounts={accounts} movements={data.movements}/>} {workspace==='installments'&&<InstallmentsView data={data} obligations={obligations} onDetail={onDetail} onModal={onModal}/>} {workspace==='recurring'&&<RecurringView data={data} obligations={obligations} onDetail={onDetail} onModal={onModal} busy={busy} onRun={onRun}/>}</div>}</section></div>}

function TodayView({obligations,accounts,onDetail}){const today=localToday();const d7=new Date(`${today}T12:00:00`);d7.setDate(d7.getDate()+7);const next7=`${d7.getFullYear()}-${String(d7.getMonth()+1).padStart(2,'0')}-${String(d7.getDate()).padStart(2,'0')}`;const open=obligations.filter(x=>['open','partial'].includes(x.status));const overdue=open.filter(x=>x.dueDate<today),overdueReceivable=overdue.filter(x=>x.direction==='receivable'),overduePayable=overdue.filter(x=>x.direction==='payable'),dueToday=open.filter(x=>x.dueDate===today),week=open.filter(x=>x.dueDate>today&&x.dueDate<=next7);const balance=accounts.filter(x=>x.active).reduce((s,x)=>s+x.balance,0);const rec7=[...dueToday,...week].filter(x=>x.direction==='receivable').reduce((s,x)=>s+x.remaining,0),pay7=[...dueToday,...week].filter(x=>x.direction==='payable').reduce((s,x)=>s+x.remaining,0);return <><div className={styles.metrics} style={{gridTemplateColumns:'repeat(5,minmax(0,1fr))'}}><Metric label="Saldo atual" value={money(balance)}/><Metric label="A receber vencido" value={money(overdueReceivable.reduce((s,x)=>s+x.remaining,0))} danger={overdueReceivable.length>0}/><Metric label="A pagar vencido" value={money(overduePayable.reduce((s,x)=>s+x.remaining,0))} danger={overduePayable.length>0}/><Metric label="A receber • 7 dias" value={money(rec7)}/><Metric label="A pagar • 7 dias" value={money(pay7)}/></div><div className={styles.todayGrid} style={{gridTemplateColumns:'repeat(2,minmax(0,1fr))'}}><ObligationSection title="Recebimentos vencidos" items={overdueReceivable} onDetail={onDetail} empty="Nenhum recebimento vencido." danger/><ObligationSection title="Pagamentos vencidos" items={overduePayable} onDetail={onDetail} empty="Nenhum pagamento vencido." danger/><ObligationSection title="Vence hoje" items={dueToday} onDetail={onDetail} empty="Nada vence hoje."/><ObligationSection title="Próximos 7 dias" items={week} onDetail={onDetail} empty="Nenhum compromisso nos próximos 7 dias."/></div></>}
function Metric({label,value,danger}){return <article className={`${styles.metric} ${danger?styles.metricDanger:''}`}><small>{label}</small><strong>{value}</strong></article>}
function ObligationSection({title,items,onDetail,empty,danger}){return <section className={styles.panel}><header><h2>{title}</h2><span>{items.length}</span></header>{!items.length?<div className={styles.empty}>{empty}</div>:<div className={styles.obList}>{[...items].sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))).map(x=><button key={x.id} onClick={()=>onDetail(x)}><i className={x.direction==='receivable'?styles.inDot:styles.outDot}/><div><b>{x.description}</b><small>{dateBR(x.dueDate)} • {x.direction==='receivable'?'Receber':'Pagar'}</small></div><strong className={danger?styles.dangerText:''}>{money(x.remaining)}</strong></button>)}</div>}</section>}

function StatementView({accounts,movements}){const [accountId,setAccountId]=useState(accounts[0]?.id||'');const [month,setMonth]=useState(monthNow());const account=accounts.find(x=>x.id===accountId);const start=`${month}-01`;const [y,m]=month.split('-').map(Number);const end=`${month}-${String(new Date(Date.UTC(y,m,0)).getUTCDate()).padStart(2,'0')}`;const opening=(account&&String(account.openingDate).slice(0,10)<start?account.openingBalance:0)+movements.filter(x=>x.accountId===accountId&&String(x.date).slice(0,10)<start).reduce((s,x)=>s+(x.direction==='in'?x.amount:-x.amount),0);let running=opening;const rows=movements.filter(x=>x.accountId===accountId&&String(x.date).slice(0,10)>=start&&String(x.date).slice(0,10)<=end).sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.createdAt).localeCompare(String(b.createdAt))).map(x=>({...x,running:(running+=x.direction==='in'?x.amount:-x.amount)}));return <><div className={styles.filters}><label>Conta<select value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Mês<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div><small>Saldo inicial do período</small><strong>{money(opening)}</strong></div></div><section className={styles.tablePanel}><table><thead><tr><th>Data</th><th>Movimento</th><th>Entrada</th><th>Saída</th><th>Saldo</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{dateBR(r.date)}</td><td><b>{r.description}</b><small>{r.kind}</small></td><td className={styles.inText}>{r.direction==='in'?money(r.amount):'—'}</td><td className={styles.outText}>{r.direction==='out'?money(r.amount):'—'}</td><td><strong>{money(r.running)}</strong></td></tr>)}{!rows.length&&<tr><td colSpan="5"><div className={styles.empty}>Sem movimentos no período.</div></td></tr>}</tbody></table></section></>}

function InstallmentsView({data,obligations,onDetail,onModal}){const company=data.companies[0];const plans=data.installmentPlans.filter(x=>x.companyId===company?.id);return <><div className={styles.toolbar}><div><h2>Parcelamentos</h2><p>Cada parcela é uma obrigação independente, mas permanece agrupada.</p></div><button onClick={()=>onModal({type:'new-plan'})}><Icon name="plus"/>Novo parcelamento</button></div><div className={styles.cardGrid}>{plans.map(plan=>{const members=data.installmentMembers.filter(m=>m.planId===plan.id).sort((a,b)=>a.installmentNo-b.installmentNo);const obs=members.map(m=>obligations.find(o=>o.id===m.obligationId)).filter(Boolean);const paid=obs.filter(o=>o.status==='settled').length;const remaining=obs.reduce((s,o)=>s+(o.status==='cancelled'?0:o.remaining),0);const displayStatus=paid===plan.installmentCount?'completed':plan.status;return <article className={styles.groupCard} key={plan.id}><header><div><small>{plan.direction==='receivable'?'A receber':'A pagar'}</small><h3>{plan.description}</h3></div><span className={displayStatus==='active'?styles.activeBadge:styles.mutedBadge}>{displayStatus}</span></header><div className={styles.groupStats}><div><small>Total original</small><b>{money(plan.totalAmount)}</b></div><div><small>Parcelas quitadas</small><b>{paid}/{plan.installmentCount}</b></div><div><small>Saldo aberto</small><b>{money(remaining)}</b></div></div><div className={styles.installmentRows}>{obs.map((o,i)=><button key={o.id} onClick={()=>onDetail(o)}><span>{i+1}/{plan.installmentCount}</span><b>{dateBR(o.dueDate)}</b><strong>{money(o.remaining)}</strong></button>)}</div>{plan.status==='active'&&displayStatus!=='completed'&&<footer><button className={styles.linkDanger} onClick={()=>onModal({type:'cancel-plan',plan})}>Cancelar saldo restante</button></footer>}</article>})}{!plans.length&&<div className={styles.bigEmpty}>Nenhum parcelamento cadastrado.</div>}</div></>}

function RecurringView({data,obligations,onDetail,onModal,busy,onRun}){const company=data.companies[0];const rules=data.recurringRules.filter(x=>x.companyId===company?.id);return <><div className={styles.toolbar}><div><h2>Recorrências</h2><p>Aluguel, internet, contratos, mensalidades e receitas recorrentes.</p></div><button onClick={()=>onModal({type:'new-recurring'})}><Icon name="plus"/>Nova recorrência</button></div><div className={styles.cardGrid}>{rules.map(rule=>{const members=data.recurringMembers.filter(m=>m.recurringId===rule.id);const obs=members.map(m=>obligations.find(o=>o.id===m.obligationId)).filter(Boolean).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)));return <article className={styles.groupCard} key={rule.id}><header><div><small>{rule.direction==='receivable'?'Receita recorrente':'Despesa recorrente'}</small><h3>{rule.description}</h3></div><span className={rule.active?styles.activeBadge:styles.mutedBadge}>{rule.active?'Ativa':'Encerrada'}</span></header><div className={styles.groupStats}><div><small>Valor mensal</small><b>{money(rule.amount)}</b></div><div><small>Vence dia</small><b>{rule.dueDay}</b></div><div><small>Gerada até</small><b>{dateBR(rule.generatedThrough)}</b></div></div><div className={styles.installmentRows}>{obs.slice(-6).map(o=><button key={o.id} onClick={()=>onDetail(o)}><span>{dateBR(o.dueDate)}</span><b>{o.status}</b><strong>{money(o.remaining)}</strong></button>)}</div>{rule.active&&<footer><button onClick={()=>onRun(()=>generateRecurringV2({ruleId:rule.id,through:addMonths(rule.generatedThrough||rule.startsOn,6)}),'Mais 6 meses gerados.')} disabled={busy}>Gerar +6 meses</button><button className={styles.linkDanger} onClick={()=>onModal({type:'stop-recurring',rule})}>Encerrar</button></footer>}</article>})}{!rules.length&&<div className={styles.bigEmpty}>Nenhuma recorrência cadastrada.</div>}</div></>}

function ObligationDrawer({obligation,data,onClose,onEdit}){const settlements=data.settlements.filter(x=>x.obligationId===obligation.id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const revisions=data.revisions.filter(x=>x.obligation_id===obligation.id).sort((a,b)=>String(b.changed_at).localeCompare(String(a.changed_at)));const counterparty=(obligation.direction==='receivable'?data.customers:data.suppliers).find(x=>x.id===(obligation.customerId||obligation.supplierId));const category=data.categories.find(x=>x.id===obligation.categoryId);return <div className={styles.drawerBackdrop} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className={styles.drawer}><header><div><small>{obligation.direction==='receivable'?'Conta a receber':'Conta a pagar'}</small><h2>{obligation.description}</h2></div><button onClick={onClose}><Icon name="close"/></button></header><div className={styles.drawerAmount}><small>Saldo em aberto</small><strong>{money(obligation.remaining)}</strong><span>Original {money(obligation.originalAmount)} • baixado {money(obligation.settledAmount)}</span></div><dl><div><dt>Vencimento</dt><dd>{dateBR(obligation.dueDate)}</dd></div><div><dt>Status</dt><dd>{obligation.displayStatus}</dd></div><div><dt>{obligation.direction==='receivable'?'Cliente':'Fornecedor'}</dt><dd>{counterparty?.name||'Não informado'}</dd></div><div><dt>Categoria</dt><dd>{category?.name||'Sem categoria'}</dd></div><div><dt>Origem</dt><dd>{obligation.origin}</dd></div><div><dt>Observação</dt><dd>{obligation.notes||'—'}</dd></div></dl>{['open','partial'].includes(obligation.status)&&<button className={styles.editButton} onClick={onEdit}><Icon name="edit"/>Editar com histórico</button>}<section className={styles.drawerSection}><h3>Baixas</h3>{settlements.map(s=><div className={styles.auditRow} key={s.id}><div><b>{money(s.amount)}</b><small>{dateBR(s.date)} • {s.status}</small></div><span>{data.accounts.find(a=>a.id===s.accountId)?.name||'Conta'}</span></div>)}{!settlements.length&&<p>Nenhuma baixa.</p>}</section><section className={styles.drawerSection}><h3>Alterações</h3>{revisions.map(r=><div className={styles.auditRow} key={r.id}><div><b>{r.reason}</b><small>{new Date(r.changed_at).toLocaleString('pt-BR')}</small></div></div>)}{!revisions.length&&<p>Nenhuma edição registrada.</p>}</section></aside></div>}

function EditObligationModal({obligation,data,busy,onClose,onSave}){const [f,setF]=useState({description:obligation.description,issueDate:String(obligation.issueDate||'').slice(0,10),dueDate:String(obligation.dueDate).slice(0,10),amount:obligation.originalAmount,customerId:obligation.customerId||'',supplierId:obligation.supplierId||'',categoryId:obligation.categoryId||'',notes:obligation.notes||'',reason:''});const patch=(k,v)=>setF(x=>({...x,[k]:v}));const parties=obligation.direction==='receivable'?data.customers:data.suppliers;return <Modal title="Editar obrigação" desc="A alteração será registrada no histórico." onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({...f,customerId:f.customerId||null,supplierId:f.supplierId||null,categoryId:f.categoryId||null})}}><Field label="Descrição"><input required value={f.description} onChange={e=>patch('description',e.target.value)}/></Field><div className={styles.formGrid}><Field label="Emissão"><input type="date" value={f.issueDate} onChange={e=>patch('issueDate',e.target.value)}/></Field><Field label="Vencimento"><input required type="date" value={f.dueDate} onChange={e=>patch('dueDate',e.target.value)}/></Field></div><div className={styles.formGrid}><Field label="Valor"><input required min={obligation.settledAmount||0.01} step="0.01" type="number" value={f.amount} onChange={e=>patch('amount',e.target.value)}/></Field><Field label={obligation.direction==='receivable'?'Cliente':'Fornecedor'}><select value={obligation.direction==='receivable'?f.customerId:f.supplierId} onChange={e=>patch(obligation.direction==='receivable'?'customerId':'supplierId',e.target.value)}><option value="">Não informado</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></div><Field label="Categoria"><select value={f.categoryId} onChange={e=>patch('categoryId',e.target.value)}><option value="">Sem categoria</option>{data.categories.filter(c=>c.type===(obligation.direction==='receivable'?'revenue':'expense')).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Observação"><textarea rows="2" value={f.notes} onChange={e=>patch('notes',e.target.value)}/></Field><Field label="Motivo da alteração"><textarea required rows="3" value={f.reason} onChange={e=>patch('reason',e.target.value)} placeholder="Ex.: vencimento renegociado com o fornecedor"/></Field><Actions busy={busy} onClose={onClose}/></form></Modal>}

function InstallmentModal({data,busy,onClose,onSave}){const company=data.companies[0];const [f,setF]=useState({organizationId:company.id,direction:'payable',description:'',totalAmount:'',installmentCount:2,issueDate:localToday(),firstDueDate:localToday(),customerId:'',supplierId:'',categoryId:'',notes:''});const patch=(k,v)=>setF(x=>({...x,[k]:v}));const parties=f.direction==='receivable'?data.customers:data.suppliers;return <Modal title="Novo parcelamento" desc="O sistema criará uma obrigação para cada parcela." onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({...f,customerId:f.direction==='receivable'?f.customerId||null:null,supplierId:f.direction==='payable'?f.supplierId||null:null,categoryId:f.categoryId||null})}}><div className={styles.formGrid}><Field label="Tipo"><select value={f.direction} onChange={e=>patch('direction',e.target.value)}><option value="payable">A pagar</option><option value="receivable">A receber</option></select></Field><Field label={f.direction==='receivable'?'Cliente':'Fornecedor'}><select value={f.direction==='receivable'?f.customerId:f.supplierId} onChange={e=>patch(f.direction==='receivable'?'customerId':'supplierId',e.target.value)}><option value="">Não informado</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></div><Field label="Descrição"><input required value={f.description} onChange={e=>patch('description',e.target.value)}/></Field><div className={styles.formGrid}><Field label="Valor total"><input required min="0.01" step="0.01" type="number" value={f.totalAmount} onChange={e=>patch('totalAmount',e.target.value)}/></Field><Field label="Parcelas"><input required min="2" max="120" type="number" value={f.installmentCount} onChange={e=>patch('installmentCount',e.target.value)}/></Field></div><div className={styles.formGrid}><Field label="Emissão"><input type="date" value={f.issueDate} onChange={e=>patch('issueDate',e.target.value)}/></Field><Field label="1º vencimento"><input required type="date" value={f.firstDueDate} onChange={e=>patch('firstDueDate',e.target.value)}/></Field></div><Field label="Categoria"><select value={f.categoryId} onChange={e=>patch('categoryId',e.target.value)}><option value="">Sem categoria</option>{data.categories.filter(c=>c.type===(f.direction==='receivable'?'revenue':'expense')).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Observação"><textarea rows="2" value={f.notes} onChange={e=>patch('notes',e.target.value)}/></Field><Actions busy={busy} onClose={onClose}/></form></Modal>}

function RecurringModal({data,busy,onClose,onSave}){const company=data.companies[0];const [f,setF]=useState({organizationId:company.id,direction:'payable',description:'',amount:'',dueDay:new Date().getDate(),startsOn:localToday(),endsOn:'',customerId:'',supplierId:'',categoryId:'',notes:'',generateMonths:12});const patch=(k,v)=>setF(x=>({...x,[k]:v}));const parties=f.direction==='receivable'?data.customers:data.suppliers;return <Modal title="Nova recorrência" desc="As próximas competências serão geradas como obrigações normais." onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({...f,endsOn:f.endsOn||null,customerId:f.direction==='receivable'?f.customerId||null:null,supplierId:f.direction==='payable'?f.supplierId||null:null,categoryId:f.categoryId||null})}}><div className={styles.formGrid}><Field label="Tipo"><select value={f.direction} onChange={e=>patch('direction',e.target.value)}><option value="payable">Despesa recorrente</option><option value="receivable">Receita recorrente</option></select></Field><Field label={f.direction==='receivable'?'Cliente':'Fornecedor'}><select value={f.direction==='receivable'?f.customerId:f.supplierId} onChange={e=>patch(f.direction==='receivable'?'customerId':'supplierId',e.target.value)}><option value="">Não informado</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></div><Field label="Descrição"><input required value={f.description} onChange={e=>patch('description',e.target.value)}/></Field><div className={styles.formGrid}><Field label="Valor mensal"><input required min="0.01" step="0.01" type="number" value={f.amount} onChange={e=>patch('amount',e.target.value)}/></Field><Field label="Dia do vencimento"><input required min="1" max="31" type="number" value={f.dueDay} onChange={e=>patch('dueDay',e.target.value)}/></Field></div><div className={styles.formGrid}><Field label="Início"><input required type="date" value={f.startsOn} onChange={e=>patch('startsOn',e.target.value)}/></Field><Field label="Fim (opcional)"><input type="date" value={f.endsOn} onChange={e=>patch('endsOn',e.target.value)}/></Field></div><Field label="Categoria"><select value={f.categoryId} onChange={e=>patch('categoryId',e.target.value)}><option value="">Sem categoria</option>{data.categories.filter(c=>c.type===(f.direction==='receivable'?'revenue':'expense')).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Actions busy={busy} onClose={onClose}/></form></Modal>}

function StopRecurringModal({busy,onClose,onSave}){const [reason,setReason]=useState(''),[cancelScope,setCancelScope]=useState('next_month');return <Modal title="Encerrar recorrência" desc="Escolha exatamente o que deve acontecer com as obrigações que já foram geradas." onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(reason,cancelScope)}}><Field label="O que fazer com as obrigações já geradas?"><div style={{display:'grid',gap:8}}><label className={styles.checkbox}><input type="radio" name="cancelScope" value="keep" checked={cancelScope==='keep'} onChange={e=>setCancelScope(e.target.value)}/><span><b>Só parar novas gerações</b><br/><small>As obrigações já criadas permanecem exatamente como estão.</small></span></label><label className={styles.checkbox}><input type="radio" name="cancelScope" value="next_month" checked={cancelScope==='next_month'} onChange={e=>setCancelScope(e.target.value)}/><span><b>Cancelar a partir do próximo mês</b><br/><small>Mantém o mês atual e cancela obrigações abertas das competências seguintes.</small></span></label><label className={styles.checkbox}><input type="radio" name="cancelScope" value="all_open" checked={cancelScope==='all_open'} onChange={e=>setCancelScope(e.target.value)}/><span><b>Cancelar abertas a partir de hoje</b><br/><small>Cancela também obrigações abertas do mês atual com vencimento hoje ou depois.</small></span></label></div></Field><Field label="Motivo"><textarea required rows="4" value={reason} onChange={e=>setReason(e.target.value)}/></Field><Actions busy={busy} onClose={onClose} danger/></form></Modal>}
function ReasonModal({title,text,busy,onClose,onSave}){const [reason,setReason]=useState('');return <Modal title={title} desc={text} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(reason)}}><Field label="Motivo"><textarea required rows="4" value={reason} onChange={e=>setReason(e.target.value)}/></Field><Actions busy={busy} onClose={onClose} danger/></form></Modal>}
function Modal({title,desc,onClose,children}){return <div className={styles.modalBackdrop} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={styles.modal}><header><div><h2>{title}</h2><p>{desc}</p></div><button onClick={onClose}><Icon name="close"/></button></header>{children}</section></div>}
function Field({label,children}){return <label className={styles.field}><span>{label}</span>{children}</label>}
function Actions({busy,onClose,danger=false}){return <footer className={styles.actions}><button type="button" onClick={onClose}>Voltar</button><button className={danger?styles.dangerButton:styles.primaryButton} disabled={busy}>{busy?'Salvando…':'Salvar'}</button></footer>}
